\set ON_ERROR_STOP on

-- Schema-only setup for InvoiceDoc2 (Lab 7 baseline)
-- Safe to run multiple times: creates missing tables and indexes only.
-- For Lab 8 changes (sales_person + invoice FK), run: 002_lab8_sales_person.sql

create table if not exists country (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table if not exists units (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table if not exists customer (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  address_line1 text,
  address_line2 text,
  country_id bigint references country(id) on delete restrict on update cascade,
  credit_limit numeric(12,2)
);

create table if not exists product (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  units_id bigint references units(id) on delete restrict on update cascade,
  unit_price numeric(12,2)
);

create table if not exists invoice (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_no text unique not null,
  invoice_date date,
  customer_id bigint references customer(id) on delete restrict on update cascade,
  total_amount numeric(12,2),
  vat numeric(12,2),
  amount_due numeric(12,2)
);

create table if not exists invoice_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_id bigint not null references invoice(id) on delete cascade on update cascade,
  product_id bigint not null references product(id) on delete restrict on update cascade,
  quantity numeric(12,2),
  unit_price numeric(12,2),
  extended_price numeric(12,2),
  unique (invoice_id, product_id)
);

create index if not exists idx_invoice_date on invoice(invoice_date);
create index if not exists idx_line_invoice on invoice_line_item(invoice_id);
create index if not exists idx_line_product on invoice_line_item(product_id);

create table if not exists receipt_header (
  receipt_id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  receipt_no text unique not null,
  receipt_date date not null,
  customer_id bigint not null references customer(id) on delete restrict on update cascade,
  payment_method text not null check (payment_method in ('cash', 'bank_transfer', 'check')),
  payment_notes text,
  total_received numeric(12,2) not null default 0 check (total_received >= 0),
  check (receipt_no ~ '^RCT[0-9]{2}-[0-9]{5}$')
);

create table if not exists receipt_line (
  receipt_line_id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  receipt_id bigint not null references receipt_header(receipt_id) on delete cascade on update cascade,
  invoice_id bigint not null references invoice(id) on delete restrict on update cascade,
  full_amount_due numeric(12,2) not null check (full_amount_due >= 0),
  amount_already_received numeric(12,2) not null default 0 check (amount_already_received >= 0),
  amount_remaining numeric(12,2) not null check (amount_remaining >= 0),
  amount_received_here numeric(12,2) not null check (amount_received_here >= 0),
  amount_still_remaining numeric(12,2) not null check (amount_still_remaining >= 0),
  unique (receipt_id, invoice_id),
  check (amount_remaining = full_amount_due - amount_already_received),
  check (amount_still_remaining = amount_remaining - amount_received_here),
  check (amount_received_here <= amount_remaining)
);

create index if not exists idx_receipt_header_date on receipt_header(receipt_date);
create index if not exists idx_receipt_header_customer on receipt_header(customer_id);
create index if not exists idx_receipt_line_receipt on receipt_line(receipt_id);
create index if not exists idx_receipt_line_invoice on receipt_line(invoice_id);

create or replace view invoice_received_view as
select
  i.customer_id,
  i.id as invoice_id,
  i.invoice_no,
  coalesce(i.amount_due, 0)::numeric(12,2) as amount_due,
  coalesce(sum(rl.amount_received_here), 0)::numeric(12,2) as amount_received,
  greatest(coalesce(i.amount_due, 0) - coalesce(sum(rl.amount_received_here), 0), 0)::numeric(12,2) as amount_remain
from invoice i
left join receipt_line rl on rl.invoice_id = i.id
group by i.customer_id, i.id, i.invoice_no, i.amount_due;

create or replace function refresh_receipt_total()
returns trigger as $$
declare
  target_receipt_id bigint;
begin
  target_receipt_id := coalesce(new.receipt_id, old.receipt_id);

  update receipt_header rh
  set total_received = coalesce((
    select sum(rl.amount_received_here)
    from receipt_line rl
    where rl.receipt_id = target_receipt_id
  ), 0)
  where rh.receipt_id = target_receipt_id;

  return null;
end;
$$ language plpgsql;

drop trigger if exists trg_receipt_line_refresh_total on receipt_line;
create trigger trg_receipt_line_refresh_total
after insert or update or delete on receipt_line
for each row execute function refresh_receipt_total();
