-- สร้าง sales_person table (ถ้ายังไม่มี)
create table if not exists sales_person (
  id             bigint primary key generated by default as identity,
  created_at     timestamp default now(),
  code           text unique not null,
  name           text not null,
  start_work_date date    -- วันที่เริ่มงาน
);

-- เพิ่ม FK column ใน invoice โดยไม่ต้อง drop table
alter table invoice
  add column if not exists sales_person_id bigint references sales_person(id)
    on delete set null   -- ถ้าลบ sales person ควรเกิดอะไรกับ invoice?
    on update cascade;

-- ใส่ข้อมูลตัวอย่าง (ON CONFLICT DO NOTHING = rerun ได้ปลอดภัย)
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (1, '2026-01-01 00:00:00+00', 'SP001', 'Alice', '2024-01-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (2, '2026-01-01 00:00:00+00', 'SP002', 'Bob', '2024-02-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (3, '2026-01-01 00:00:00+00', 'SP003', 'Charlie', '2024-03-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (4, '2026-01-01 00:00:00+00', 'SP004', 'David', '2024-04-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (5, '2026-01-01 00:00:00+00', 'SP005', 'Eve', '2024-05-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (6, '2026-01-01 00:00:00+00', 'SP006', 'Frank', '2024-06-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (7, '2026-01-01 00:00:00+00', 'SP007', 'Grace', '2024-07-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (8, '2026-01-01 00:00:00+00', 'SP008', 'Heidi', '2024-08-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (9, '2026-01-01 00:00:00+00', 'SP009', 'Ivan', '2024-09-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, created_at, code, name, start_work_date) VALUES (10, '2026-01-01 00:00:00+00', 'SP010', 'Judy', '2024-10-01') ON CONFLICT DO NOTHING;

-- Reset Sequence
SELECT setval(pg_get_serial_sequence('sales_person', 'id'), coalesce(max(id), 0) + 1, false) FROM sales_person;
